# Generated by Django 3.0.7 on 2020-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='status',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='listening',
            name='image',
            field=models.ImageField(blank=True, upload_to='listings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listening',
            name='image2',
            field=models.ImageField(blank=True, upload_to='listings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listening',
            name='image3',
            field=models.ImageField(blank=True, upload_to='listings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listening',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
