# Generated by Django 3.0.7 on 2020-06-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200610_1526'),
        ('shelter', '0002_auto_20200610_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.Agents'),
            preserve_default=False,
        ),
    ]
