# Generated by Django 3.0.7 on 2020-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_listening_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quickcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('textarea', models.TextField(max_length=200)),
            ],
        ),
    ]
