# Generated by Django 3.0.7 on 2020-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_quickcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCotact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentname', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_subject', models.TextField(max_length=200)),
            ],
        ),
    ]
