# Generated by Django 3.0.7 on 2020-06-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_agentcotact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentCotact',
            new_name='AgentContact',
        ),
    ]
