# Generated by Django 3.0.7 on 2020-06-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20200610_1226'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Agents',
        ),
    ]
